version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:password@postgres/finance_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: "your-secret-key-here"
      ALGORITHM: "HS256"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend/nextjs-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/nextjs-app:/app

volumes:
  postgres_data:
  redis_data: 